/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using System.Collections.Generic;
using UnityEngine;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using F8Framework.Core;

namespace F8Framework.F8DataManager
{
	public class F8DataManager : Singleton<F8DataManager>
	{
		public void LoadAll()
		{
			
		}

		public void RuntimeLoadAll(Dictionary<String, System.Object> objs)
		{
			
		}

		private System.Object Load(string name)
		{
			IFormatter f = new BinaryFormatter();
			TextAsset text = AssetManager.Instance.Load<TextAsset>(name);
			Stream s = new MemoryStream(text.bytes);
			System.Object obj = f.Deserialize(s);
			s.Close();
			return obj;
		}
	}
}
